spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
server:
  port: 8080
  servlet:
    context-path: "/weather"
logging:
  level:
    root: INFO
    org.apache.http: WARN


app:
  supported-cities: ${SUPPORTED_CITIES:SYDNEY,BRISBANE,ADELAIDE,CANBERRA,PERTH,DARWIN}
  retrieve-interval: ${RETRIEVE_INTERVAL:900}
  open-weather-api-key: ${OPEN_WEATHER_API_KEY}
  open-weather-url: ${OPEN_WEATHER_API_URL}