spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    root: ERROR
    org.apache.http: WARN
    org.testcontainers: INFO
    com.github.dockerjava: WARN